/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Color;
import java.util.Scanner;


/**
 *
 * @author ta2er
 */
public class MainFrame extends javax.swing.JFrame {
	   // Variables declaration - do not modify                     
    private javax.swing.JLabel CD1;
    private javax.swing.JLabel CD2;
    private javax.swing.JLabel CD3;
    private javax.swing.JLabel CD4;
    private javax.swing.JLabel CD5;
    private javax.swing.JLabel CP1;
    private javax.swing.JLabel CP2;
    private javax.swing.JLabel CP3;
    private javax.swing.JLabel CP4;
    private javax.swing.JLabel CP5;
    private java.awt.Label DeSum;
    private javax.swing.JButton Deal;
    private javax.swing.JTextField DealerScore;
    private javax.swing.JButton Help;
    private javax.swing.JButton Hit;
    private javax.swing.JTextField MyScore;
    private java.awt.Label MySum;
    private javax.swing.JButton NG;
    private javax.swing.JButton Out;
    private javax.swing.JButton Save;
    private javax.swing.JButton Stand;
    private javax.swing.JInternalFrame jInternalFrame1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    // End of variables declaration 

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
                            
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        Save = new javax.swing.JButton();
        Hit = new javax.swing.JButton();
        Stand = new javax.swing.JButton();
        Deal = new javax.swing.JButton();
        NG = new javax.swing.JButton();
        Help = new javax.swing.JButton();
        Out = new javax.swing.JButton();
        MyScore = new javax.swing.JTextField();
        DealerScore = new javax.swing.JTextField();
        MySum = new java.awt.Label();
        DeSum = new java.awt.Label();
        CP1 = new javax.swing.JLabel();
        CP2 = new javax.swing.JLabel();
        CD2 = new javax.swing.JLabel();
        CP3 = new javax.swing.JLabel();
        CP4 = new javax.swing.JLabel();
        CP5 = new javax.swing.JLabel();
        CD3 = new javax.swing.JLabel();
        CD4 = new javax.swing.JLabel();
        CD5 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        CD1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 0, 0));
        setIconImage(getIconImage());

        jInternalFrame1.setBackground(new java.awt.Color(255, 255, 255));
        jInternalFrame1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setTitle("BlackJack");
        jInternalFrame1.setFrameIcon(null);
        jInternalFrame1.setMinimumSize(new java.awt.Dimension(500, 500));
        jInternalFrame1.setName(""); // NOI18N
        jInternalFrame1.setVisible(true);

        Save.setText("Save");

        Hit.setBackground(new java.awt.Color(0, 204, 51));
        Hit.setText("HIT");
        Hit.setEnabled(false);
        Hit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitActionPerformed(evt);
            }
        });

        Stand.setBackground(new java.awt.Color(204, 0, 0));
        Stand.setText("Stand");
        Stand.setEnabled(false);
        Stand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StandActionPerformed(evt);
            }
        });

        Deal.setBackground(new java.awt.Color(153, 0, 153));
        Deal.setText("Deal");
        Deal.setEnabled(false);
        Deal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DealActionPerformed(evt);
            }
        });

        NG.setBackground(new java.awt.Color(255, 255, 0));
        NG.setText("New Game");
        NG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NGActionPerformed(evt);
            }
        });

        Help.setText("Help");

        Out.setText("Out");

        MyScore.setBackground(new java.awt.Color(255, 51, 255));
        MyScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyScoreActionPerformed(evt);
            }
        });

        DealerScore.setEditable(false);
        DealerScore.setBackground(new java.awt.Color(102, 204, 0));

        MySum.setForeground(new java.awt.Color(204, 0, 51));
        MySum.setText("My Score");

        DeSum.setForeground(new java.awt.Color(204, 0, 51));
        DeSum.setText("Dealer Score");

        CP1.setBackground(new java.awt.Color(255, 255, 255));
        CP1.setForeground(new java.awt.Color(255, 255, 255));
        CP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("pic/001c.gif"))); // NOI18N
        CP1.setFocusTraversalPolicyProvider(true);

        CP2.setBackground(new java.awt.Color(255, 255, 255));
        CP2.setForeground(new java.awt.Color(255, 255, 255));
        CP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("pic/010c.gif"))); // NOI18N

        CD2.setBackground(new java.awt.Color(255, 255, 255));
        CD2.setForeground(new java.awt.Color(255, 255, 255));
        CD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("pic/012h.gif"))); // NOI18N

        CP3.setBackground(new java.awt.Color(255, 255, 255));
        CP3.setForeground(new java.awt.Color(255, 255, 255));
        CP3.setIcon(new javax.swing.ImageIcon(getClass().getResource("pic/004h.gif"))); // NOI18N

        CP4.setBackground(new java.awt.Color(255, 255, 255));
        CP4.setForeground(new java.awt.Color(255, 255, 255));
        CP4.setIcon(new javax.swing.ImageIcon(getClass().getResource("pic/001c.gif"))); // NOI18N

        CP5.setBackground(new java.awt.Color(255, 255, 255));
        CP5.setForeground(new java.awt.Color(255, 255, 255));
        CP5.setIcon(new javax.swing.ImageIcon(getClass().getResource("pic/001c.gif"))); // NOI18N

        CD3.setBackground(new java.awt.Color(255, 255, 255));
        CD3.setForeground(new java.awt.Color(255, 255, 255));
        CD3.setIcon(new javax.swing.ImageIcon(getClass().getResource("pic/001c.gif"))); // NOI18N

        CD4.setBackground(new java.awt.Color(255, 255, 255));
        CD4.setForeground(new java.awt.Color(255, 255, 255));
        CD4.setIcon(new javax.swing.ImageIcon(getClass().getResource("pic/001c.gif"))); // NOI18N

        CD5.setBackground(new java.awt.Color(255, 255, 255));
        CD5.setForeground(new java.awt.Color(255, 255, 255));
        CD5.setIcon(new javax.swing.ImageIcon(getClass().getResource("pic/001c.gif"))); // NOI18N

        label1.setText("Dealer");

        label2.setText("Player");

        CD1.setBackground(new java.awt.Color(255, 255, 255));
        CD1.setForeground(new java.awt.Color(255, 255, 255));
        CD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("pic/001c.gif"))); // NOI18N

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Deal, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Stand, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                            .addComponent(NG, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                            .addComponent(Hit, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                    .addComponent(Out)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Save)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Help)))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(MySum, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(MyScore, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(76, 76, 76)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CP1)
                            .addComponent(CD1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(CP2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CP3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CP4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CP5))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(CD2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CD3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CD4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CD5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DeSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DealerScore, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(480, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Out)
                    .addComponent(Save)
                    .addComponent(Help))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MySum, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MyScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DeSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DealerScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CD2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CD3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CD4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CD5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CP1)
                            .addComponent(CP2)
                            .addComponent(CP3)
                            .addComponent(CP4)
                            .addComponent(CP5)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(NG, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Deal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(CD1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame1Layout.createSequentialGroup()
                                        .addGap(92, 92, 92)
                                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(66, 66, 66)
                                .addComponent(Hit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Stand, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 297, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1182, Short.MAX_VALUE))
        );

        try {
            jInternalFrame1.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        pack();
    }// </editor-fold>                        
/**
 * Action New Game Button 
 * @param evt
 */
    private void NGActionPerformed(java.awt.event.ActionEvent evt) {                                   
       Deal.setEnabled(true);
     CD1.setVisible(false);
     CD2.setVisible(false);
     CD3.setVisible(false);
     CD4.setVisible(false);
     CD5.setVisible(false);
     CP1.setVisible(false);
     CP2.setVisible(false);
     CP3.setVisible(false);
     CP4.setVisible(false);
     CP5.setVisible(false);
    }                                  
/**
 * Action new Round Button
 * @param evt
 */
    private void DealActionPerformed(java.awt.event.ActionEvent evt) {                                     
       
        Hit.setEnabled(true);
        Stand.setEnabled(true);
        CD1.setVisible(true);
        CD2.setVisible(true);
        CP1.setVisible(true);
        CP2.setVisible(true);
        

    }                                    
/**
 * Action Stand State Player Button
 * @param evt
 */
    private void StandActionPerformed(java.awt.event.ActionEvent evt) {                                      
      //To Do
    }                                     
/**
 * Action Hit State Player Button
 * @param evt
 */
    private void HitActionPerformed(java.awt.event.ActionEvent evt) {                                    
        CP3.setVisible(true);
    }                                   
/**
 * Set Player Score text 
 * @param evt
 */
    private void MyScoreActionPerformed(java.awt.event.ActionEvent evt) {                                        
       //To DO
    }                                       

    /**
     * @param args the command line arguments
     * Start Of Main
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       MainFrame Main= new MainFrame();
       Main.jInternalFrame1.setBackground(Color.BLUE);
       Main.setVisible(true);
        Main.Deal.setEnabled(true);
     Main.CD1.setVisible(false);
     Main.CD2.setVisible(false);
     Main.CD3.setVisible(false);
     Main.CD4.setVisible(false);
     Main.CD5.setVisible(false);
     Main.CP1.setVisible(false);
     Main.CP2.setVisible(false);
     Main.CP3.setVisible(false);
     Main.CP4.setVisible(false);
     Main.CP5.setVisible(false);
             
                
         /**
          * Output in the Console    
          */
       
        // init
		Scanner sc = new Scanner(System.in);
		Scanner Ac = new Scanner(System.in);
		// flags for when each Player is finished hitting
				boolean meDone = false;
				boolean dealerDone = false;
				String Ans;
				String To;
				// init the Player objects
				Player me = new Player("Player");
				Player dealer = new Player("Dealer");
				Deck theDeck = new Deck(1, true);
		do{
			
		theDeck.shuffle();
		me.emptyHand();
		dealer.emptyHand();
		for(int i=0;i<2;i++){
                  
		me.addCard(theDeck.dealNextCard());
		dealer.addCard(theDeck.dealNextCard());
		}

		// print initial hands
		System.out.println("Cards are dealt \n");
		me.printHand();
		System.out.println("\n");
		dealer.printHand();
		System.out.println("\n");

		

		while (!meDone || !dealerDone) {
			// player turn
			if (!meDone) {
				System.out.print("Hit or Stay ? [Enter H or S]:");
				Ans = sc.next();
				System.out.println();

				// if the player Hits
				if (Ans.equals( "H")) {
					// add next card in the deck and store whether player is
					// busted
					meDone = !me.addCard(theDeck.dealNextCard());
					me.printHand();
				} else {
					me.printHand();
					meDone = true;

				}
			}
			// dealer turn
			if (!dealerDone) {
				if (dealer.getHandSum() < 17) {
					System.out.println("\nThe dealer Hits\n");
					dealerDone = !dealer.addCard(theDeck.dealNextCard());
					dealer.printHand();
				} else {
					System.out.println("\nThe Dealer Stays\n");
					dealer.printHand();
					dealerDone = true;

				}
			}

			System.out.println();

		}
		// Close Scanner
		
		// print final Hands
		me.printHand();
		dealer.printHand();
		int MySum = me.getHandSum();
		int DealerSum = dealer.getHandSum();

		if ((MySum > DealerSum && MySum <= 21) || DealerSum > 21) {
			System.out.println("\nYour Win");
			System.out.println("My Sum:" + MySum);
                        Main.MyScore.setActionCommand(Integer.toString(MySum));
			System.out.println("Dealer Sum:" + DealerSum);

		} else {
			if ((MySum < DealerSum && DealerSum <= 21) || MySum > 21) {
				System.out.println("\nDealer Wins");
				System.out.println("My Sum:" + MySum);
				System.out.println("Dealer Sum:" + DealerSum);
			} else {
				System.out.println("\nTeko");
				System.out.println("My Sum:" + MySum);
				System.out.println("Dealer Sum:" + DealerSum);
			}
		}
		System.out.println("\nDeal Or NewGame Or Out:");
		To=Ac.next();
		System.out.println();
		if(To.equals("O")){System.out.println("\nGame Out!"); break;}
		if(To.equals("D")){System.out.println("\nNew Round");}
		if(To.equals("N")){System.out.println("\nNew Game");}
		}
		while (To.equals("D")||To.equals("N"));
		sc.close();
		Ac.close();
		
	}
    

                   
}